spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: root
    username: root
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

